### PR TITLE
Add Dark Mode support

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by bartekplus** [comment]
I've just added a more complete dark mode, available in 2022.12.29.  please test and let me know what you think.

**Comment by TotalCaesar659** [comment]
Hi @bartekplus, thank you very much and happy New Year! Looks alright, but I found two places that have to be updated to Dark Mode:
- start pages

- pop-up wordlist

P.S. Do you have an option to suggest in pop-up wordlist only those words that I added manually to Text Expander, not anything else? I tried to find but I can't. If there's not the option, could you implement it?

**Comment by bartekplus** [comment]
I've added dark color scheme to pop-up wordlist, I do not plan to change new installation page at the moment. It doesn't use bulma.css as a base and it needs rework, but don't plan to change it right now.

> P.S. Do you have an option to suggest in pop-up wordlist only those words that I added manually to Text Expander, not anything else? I tried to find but I can't. If there's not the option, could you implement it?

There is no such feature. Please open new feature request for it, I will implement it,  if I find time :)

**Comment by TotalCaesar659** [comment]
Thank you very much @bartekplus! I've added FR about it. Let your very useful extension become even better in this year :)

**Comment by TotalCaesar659** [comment]
> I've added dark color scheme to pop-up wordlist, I do not plan to change new installation page at the moment. It doesn't use bulma.css as a base and it needs rework, but don't plan to change it right now.

@bartekplus Are there any plans to add Dark Mode to installation page?

**Comment by bartekplus** [comment]
@TotalCaesar659 
No, I don't plan to change installation page.

**Pull request closed without merging**
